account/urls.py
from django.conf.urls import url
from django.urls import path
from account import views
from account.views import index

app_name = "account"

urlpatterns = [
    path('', views.index, name='index'),
    path('show/<int:form_id>/', views.show, name='show'),
    # url('', views.index, name='index')
]

accountapp/urls.py
from django.conf.urls import url
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from accountapp import views
from account.views import index
from accountapp.views import AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = "accountapp"

urlpatterns = [
    path('create/', AccountCreateView.as_view(), name='create'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('success/', views.success, name='success'),
    path('main/', views.main, name='main'),
]

webProject/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from webProject import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include("account.urls")),
    path('accounts/', include("accountapp.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/models.py
from django.db import models


class Data(models.Model):
    uid = models.CharField(max_length=30)
    passwd = models.CharField(max_length=30)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.uid


class Photo(models.Model):
    data = models.ForeignKey(Data, on_delete=models.CASCADE, null=True)
    image = models.ImageField(upload_to='image/', blank=True, null=True)

accountapp/models.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.db import models
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView


class AccountCreateView(CreateView):
    model = User
    form_class = UserCreationForm
    success_url = reverse_lazy('accountapp:success')
    template_name = 'create.html'


def success(request):
    return render(request, 'success.html')

accountapp/forms.py
from django.contrib.auth.forms import UserCreationForm


class AccountUpdateForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].disabled = True

account/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.utils import timezone
from account.models import Data, Photo


def index(request):
    if request.method == "POST":
        form = Data()
        form.uid = request.POST.get('uid')
        form.passwd = request.POST.get('passwd')
        form.pub_date = timezone.datetime.now()
        form.save()
        for img in request.FILES.getlist('image'):
            photo = Photo()
            photo.data = form
            photo.image = img
            photo.save()
        return redirect('show/' + str(form.id), form.id)
    else:
        return render(request, 'index.html')


def show(request, form_id):
    lst = get_object_or_404(Data, pk=form_id)
    return render(request, 'show.html', {'lst': lst})

accountapp/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect, HttpResponseForbidden
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView
from accountapp.decorators import account_ownership_required
from accountapp.forms import AccountUpdateForm

has_decorator = [login_required, account_ownership_required]


class AccountCreateView(CreateView):
    model = User
    form_class = UserCreationForm
    success_url = reverse_lazy('accountapp:success')
    template_name = 'create.html'


class AccountDetailView(DetailView):
    model = User
    context_object_name = 'target_user'
    template_name = 'detail.html'

    # def get(self, *args, **kwargs):
    #     if self.request.user.is_authenticated and self.get_object() == self.request.user:
    #         return super().get(*args, **kwargs)
    #     else:
    #         return HttpResponseForbidden()


@method_decorator(has_decorator, 'get')
@method_decorator(has_decorator, 'post')
class AccountUpdateView(UpdateView):
    model = User
    context_object_name = 'target_user'
    form_class = AccountUpdateForm
    success_url = reverse_lazy('accountapp:main')
    template_name = 'update.html'

    # def get(self, *args, **kwargs):
    #     if self.request.user.is_authenticated and self.get_object() == self.request.user:
    #         return super().get(*args, **kwargs)
    #     else:
    #         return HttpResponseForbidden()


@method_decorator(has_decorator, 'get')
@method_decorator(has_decorator, 'post')
class AccountDeleteView(DeleteView):
    model = User
    success_url = reverse_lazy('accountapp:login')
    template_name = 'delete.html'

    # def get(self, *args, **kwargs):
    #     if self.request.user.is_authenticated and self.get_object() == self.request.user:
    #         return super().get(*args, **kwargs)
    #     else:
    #         return HttpResponseForbidden()


def success(request):
    return render(request, 'success.html')


@login_required
def main(request):
    return render(request, 'main.html')

accountapp/templates/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block contents %}
<div style="text-align: center; max-width: 500px; margin: 4rem auto">
    <div>
        <h1>회원가입</h1>
    </div>
    <div>
        <form action="{% url 'accountapp:create' %}" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" value="Confirm" class="btn btn-dark rounded-pill col-6 mt-3">
        </form>
    </div>
</div>
{% endblock %}

accountapp/templates/delete.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block contents %}
<div style="text-align: center; max-width: 500px; margin: 4rem auto">
    <div>
        <h1>회원탈퇴</h1>
    </div>
    <div>
        <form action="{% url 'accountapp:delete' pk=user.pk %}" method="post">
            {% csrf_token %}
            <input type="submit" value="Secede" class="btn btn-danger rounded-pill col-6 mt-3">
        </form>
    </div>
</div>
{% endblock %}

accountapp/templates/detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block contents %}
<div style="text-align: center; max-width: 500px; margin: 4rem auto">
    <div>
        <h1>회원정보</h1>
    </div>
    <div>
        <p>
            가입날짜: {{ target_user.date_joined }}
        </p>
        <p>
            사용자명: {{ target_user.username }}
        </p>
        <p>
            {% if target_user == user %}
                <a href="{% url 'accountapp:update' pk=target_user.pk %}">
                    회원수정
                </a>
                <a href="{% url 'accountapp:delete' pk=target_user.pk %}">
                    회원탈퇴
                </a>
            {% endif %}
        </p>
    </div>
</div>
{% endblock %}

accountapp/templates/login.html
{% extends 'base.html' %}
{% block contents %}
<div style="text-align: center">
    <div>
        <h1>로그인</h1>
    </div>
    <div>
        <form action="{% url 'accountapp:login' %}" method="post">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Confirm" class="btn btn-primary">
        </form>
    </div>
</div>
{% endblock %}

accountapp/templates/main.html
{% extends 'base.html' %}
{% block contents %}
<div style="text-align: center">
    <p></p>
    <h1>메인화면</h1>
</div>
{% endblock %}

accountapp/templates/success.html
{% extends 'base.html' %}
{% block contents %}
<div style="text-align: center">
    회원가입이 성공했습니다.
</div>
{% endblock %}

accountapp/templates/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block contents %}
<div style="text-align: center; max-width: 500px; margin: 4rem auto">
    <div>
        <h1>회원정보 수정</h1>
    </div>
    <div>
        <form action="{% url 'accountapp:update' pk=user.pk %}" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" value="Confirm" class="btn btn-dark rounded-pill col-6 mt-3">
        </form>
    </div>
</div>
{% endblock %}